.github/workflows/main.yml
Changes the integration test to run on a schedule instead of on a successful commit to master which isn't entirely useful.
* I'm testing the syntax in another repo, if that works out I'll push this up.
Right now the job runs Monday-Sunday at 2am: https://help.github.com/en/articles/events-that-trigger-workflows#scheduled-events
Closes issue #19
=> Integration Test Schedule

README.md
Improved the README examples per the discussion in issue #22
=> README Example

entrypoint.sh
Improves the commit message. 
Closes issue #29
=> Improving the commit message

lib/git.js, src/git.ts
If the working tree is clean then the deployment should be skipped. If it isn't it results in a failure which isn't a great ux.
* Add a change to the workflow file, this will mean the tree is on par with the deployment branch.
* It will fail, but exit gracefully.
* If you add an actual change, it should correctly deploy.
Closes issue #54.
=> Skips deployment if the working tree is clean

README.md
Provides an explanation and workaround on operating system support.
=> Operating System README Configuration

lib/git.js, src/git.ts
`git fetch origin` doesn't work in private repositories unless the repository path is referenced.
* With this change you should be able to deploy when the repository is private. This can be tested with `releases/v3-test`.
Closes issue #70
=> Private Repository Issue

README.md, lib/constants.js, lib/git.js, src/constants.ts, src/git.ts
Adds the ability to exclude files and folders when `CLEAN` is true.
* I'll update the README and the release with the new info.
=> Clean Excludes

__tests__/git.test.ts, lib/git.js, lib/main.js, src/git.ts, src/main.ts
Adds a series of post deployment tasks that restore the work tree to the same state as before the workflow ran.
* The deployment should occur the same as it did before. However now it should now no longer impact subsequent jobs.
Also added some emojis to the major step completion logs for visibility in the console.
=> [Issue-89] Post Deployment Tasks

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/ISSUE_TEMPLATE/SUPPORT.md
Improves the GitHub templates.
=> Improves Templates

__tests__/git.test.ts, lib/git.js, src/git.ts
Fixes an earlier bug caused by `git fetch origin`. 
* Both branch creation and deployment procceses should work with this change. To test use `JamesIves/github-pages-deploy-action@releases/v3-test`.
Closes issue #111
=> [Issue-111] Deployment Hotfix

.github/workflows/build.yml, .github/workflows/integration.yml
Improves the integration tests so they also run on push to dev.
Also added a series of additional tests that test a number of different parts of the bot.
=> Integration Test Improvements

.github/workflows/integration.yml, README.md, __tests__/execute.test.ts, lib/git.js, src/git.ts
Removes the use of `git switch` as some containers were having issues running the command. Switched all commands to their `git checkout` equivalent which is more widely supported.
* Integration tests have passed so you can just look at the results of them.
Closes issue #120
=> git switch -> git checkout

.github/workflows/integration-beta.yml
Adds additional integration tests that check prod vs beta.
=> Additional Integration Tests

__tests__/git.test.ts, lib/git.js, src/git.ts
Fixes an issue that causes a build failure with the use of `git fetch`. 
Use `releases/v3-test`. 
=> Failing Build

.github/workflows/integration-beta.yml, README.md
Pushes an update to the READmE that demonstrates how to use `actions/checkout@v2`.
N/A
=> [Issue-99] Support action/checkout@v2

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/ISSUE_TEMPLATE/SUPPORT.md
=> [Issue-138] Adds automatic issue labels

__tests__/env.js, __tests__/execute.test.ts, __tests__/git.test.ts, lib/constants.js, lib/execute.js, lib/git.js, src/constants.ts, src/execute.ts, src/git.ts
Brings test coverage up to 100%.
=> Test Coverage Improvements

.github/workflows/integration-beta.yml, .github/workflows/integration.yml, README.md, action.yml, lib/constants.js, src/constants.ts, tslint.json
Adds two options; `GIT_CONFIG_NAME` and `GIT_CONFIG_EMAIL` that allows you to override the git config used when pushing commits.
This can be tested on `releases/v3-beta` branch. 
Closes issue #153
=> Adds git config options.

README.md, __tests__/execute.test.ts, __tests__/git.test.ts, __tests__/main.test.ts, lib/constants.d.ts, lib/execute.js, lib/git.d.ts, lib/git.js, lib/lib.js, lib/util.d.ts, lib/util.js, src/execute.ts, src/git.ts, src/lib.ts, src/util.ts
=> Package Exporting Changes

CONTRIBUTING.md, __tests__/git.test.ts, __tests__/main.test.ts, package.json, src/git.ts, yarn.lock
Removes the need for an `chmod` command by using the actions/io rmRF command.
* Test with `releases/v3-test`.
Closes #247
=> Migration to actions/io rmRF

README.md
This hopefully prevents https://github.com/JamesIves/github-pages-deploy-action/issues/230 from happening again 😉
=> README: Replace `v3-test` with `v3`

__tests__/git.test.ts, src/git.ts
Adds a step which creates the target folder.
* Deploy to a target folder
Closes issue #267
=> Target Folder

README.md, __tests__/git.test.ts, __tests__/main.test.ts, action.yml, src/constants.ts, src/git.ts, src/lib.ts
Adds the ability to get a status code from the action. The action will now export either `success|failed|skipped` depending on the output. Saved as `DEPLOYMENT_STATUS`. 
* README is documented. This will be testable in the `releases/v3` branch here soon. 
This will go out with today's release.
=> Deploy Status

__tests__/git.test.ts, __tests__/main.test.ts, src/git.ts
Removes the worktree before the folder is removed.
=> Removes the worktree

src/git.ts
Adds the `--checksum` flag to the rsync command.
=> Adds Checksum Option

src/git.ts
=> Placeholder PR for Origin Check

src/git.ts
Reverts JamesIves/github-pages-deploy-action#332
=> Revert "Placeholder PR for Origin Check"

.github/dependabot.yml
Creates a `dependabot.yml` file as Dependabot is now moving natively into GitHub. 
* Nothing to test, besides ensuring that GitHub still makes appropriate pull requests against the repo. 
Closes issue #420
=> Creates Dependdabot yml file

README.md
Adds a section about support and donating to the README.
=> Adds Support to Readme

README.md
Adds details explaining how absolute folder paths work. This adjustment will go live on the release of the next version which is coming soon.
=> Absolute Folder Path README Adjustments

__tests__/git.test.ts, __tests__/main.test.ts, src/constants.ts, src/git.ts
Resolves issues #580 #579 and #582 
Guessing the origin stuff got removed by mistake as it's referenced in the tests
* Point workflow to `releases/v4-beta`, run the workflows listed in the issues!
N/A
=> Deployment Issues

.devcontainer/Dockerfile, .devcontainer/base.Dockerfile, .devcontainer/devcontainer.json
Adds support for VSCode spaces based on examples here: https://docs.github.com/en/github/developing-online-with-codespaces/configuring-codespaces-for-your-project
Run with Codespaces!
=> Dev Container -> VSCode Spaces Support

src/lib.ts
Adds an update note to the version 3 branch.
=> [Release] v3 Update Note
