- README.md
- entrypoint.sh
Now checks to see if the remote exists, and creates it. Removing a manual step in the setup process. 🎉 
Create a deploy, where the `gh-pages` branch doesn't exist. The script will now create it for you.
Then create a deploy where it does exist, it shouldn't try to create it.
> Checks if remote exists

- README.md
- entrypoint.sh
Kept running into this issue this weekend with Liza's portfolio site. If you deploy via this action with a custom domain, Github will nuke the configuration for the domain as the `CNAME` file is no longer present in the `gh-pages` branch. In order to solve this I've added an additional environment variable called `CNAME` which will add the domain record into the build directory prior to the deploy. This will maintain the GitHub configuration which will solve the issue of pages 404ing after the deploy.
* Add a CNAME record, and deploy. If you have a custom domain it will no longer 404 after the deploy.
> Push CNAME

- entrypoint.sh
Use $BASE_BRANCH instead of master in git subtree command
> Use $BASE_BRANCH instead of master

- entrypoint.sh
Currently, if the build fails (or some other part of the script), it will happily continue and force push the result to the destination.
Adding `set -e` makes sh terminate the script after any errors
> Don't push if the build fails

- entrypoint.sh
This pull request sets the `--quiet` flag on the `git commit` command. This resolves an issue where `stdout` was throwing an error because it was logging a ton of changes all at once.
This was tested by user @Rangoric in issue #24.
> Quiets the commit logs

- README.md
Just a very quick switch-a-roo on the defaults described in the readme for the `COMMIT_EMAIL` and `COMMIT_NAME` variables — they were reversed unless I'm mistaken.
Thanks!
> README: Switch COMMIT_EMAIL and COMMIT_NAME descriptions

- README.md
- entrypoint.sh
This pull request removes the requirement for `COMMIT_NAME` and `COMMIT_EMAIL`. If the event path payload has the data available it will use it, otherwise it will fall back to the `GITHUB_ACTOR` variable instead. This ensures that commits correctly come from a verified user.
If in the rare case that there's no `GITHUB_ACTOR` available, it will fall back to an email/name that shows it's from this action.
Push up a commit, it should work the same before with both a scheduled/unscheduled job.
`jq` is used to pull the information from the JSON payload.
> Removes the need for COMMIT_NAME and COMMIT_EMAIL

- README.md
- __tests__/git.test.ts
- lib/constants.js
- lib/git.js
- package.json
- src/constants.ts
- src/git.ts
- yarn.lock
Creates a `CLEAN` action variable that forces the action to remove hashed files from the deployment branch. Utilizes `rsync --delete` and ignores `CNAME` and `.nojekyll` files so they don't get deleted if this option is toggled.
* This can be used in `releases/v3-test`.
Closes issue #60.
> Automatically remove hashed files

- lib/constants.js
- lib/git.js
- src/constants.ts
- src/git.ts
As there's no `pusher` data in a scheduled job, the action will error due to it calling on `pusher.name` and `pusher.email`. This change adds a series of fallbacks, starting with the `GITHUB_ACTOR` env variable, followed by a generic string.
* The action should behave as normal, except in schedule jobs it shouldn't fail the build.
* This can be tested via `releases/v3-test`. 
Closes issue #61.
> Pusher is undefined in scheduled jobs

- __tests__/git.test.ts
- lib/git.js
- src/git.ts
Fixes an issue that prevents new branches from being generated if they don't exist on the remote.
* Switch your workflow file to use the beta version: `JamesIves/github-pages-deploy-action@releases/v3`
* Change the branch to one that doesn't exist.
* It should no longer error. Both initial and subsequent deploys should work.
I'd love to figure out how to automatically test this functionality.
> [Issue-107] Fixes an issue that prevents new branches from being created

- README.md
Fix a syntax error with an extra '-' on the full SSH example on README.md, found this while trying to use the example. No changes for build.
Using the example lead to this error: -
```
Invalid Workflow File
every step must define a `uses` or `run` key
```
Just follow along the SSH example with github actions, it should no longer say `Invalid Workflow File`
> Fix SSH example on README.md

- README.md
Hi there! I've just made a few small changes to the docs to reflect the fact that v3 no longer supports running build scripts, and any building-related steps must be done before this action.
I stuck with the `npm install` and `npm run build` example that was already there and expanded on the comments to make sure readers know to replace this step with their own build commands, or remove it entirely.
Let me know if any wording needs tweaking. Thanks! 😊
> Update readme examples to reflect the removal of build scripts

- src/git.ts
- src/lib.ts
GitHub Actions uses “…” instead of “...” in its UI. This patch aligns the messages produced by this action with that style.
> Improve messages

- src/git.ts
__*problem*__: user provided commit message being modified (appending the commit SHA).
As the user, it is a bit annoying to have the commit SHA appear twice in the commit message.
__*possible solutions:*__
* do not append the commit SHA, if user has already included it the commit message.
* let the user decide whether the user's commit message can be modified. *(maybe via argument in `action.yml`)*.
> append commit SHA to commit msg, only if not a part of it already.

- src/git.ts
This makes sure directories in `temporaryDeploymentDirectory` are writabe before attempting to remove them. Fixes: #241
> Make sure rm -rf actually works.

- src/git.ts
Fixes #297
Add --no-recurse-submodules to git fetch
Demonstrated to work in https://github.com/fredefox/cat/pull/16
> Add --no-recurse-submodules to git fetch

- .gitignore
- README.md
- __tests__/git.test.ts
- src/git.ts
Adds changes to the CNAME and nojekyll files.
> Changes to CNAME and nojekyll files

- __tests__/util.test.ts
- src/util.ts
You'd have thought `String.prototype.replace` would replace all instances right? Wrong! It only replaces the first one. `replaceAll` is coming soon but not everywhere yet.
This PR implements a `replaceAll`. It also orders the secrets by length descending, so that if one secret contains another secret inside it, both will get obfuscated. Disable the sort and you'll see the test fail.
Run the tests.
> supress secret from logs if it appears multiple times

- .eslintrc.json
- package.json
- yarn.lock
> eslint-plugin-github was updated to 4.1.1, problems with deprecated eslint rules were fixed
> Run `yarn lint`
> Bump eslint-plugin-github version + fix eslint issues

- __tests__/git.test.ts
- __tests__/util.test.ts
- src/constants.ts
- src/git.ts
- src/lib.ts
- src/util.ts
Resolves #387
Add a util function to return an absolute path of `action.folder`.
Add related tests for the function.
`yarn test`
Integration tests passed on my fork https://github.com/exuanbo/github-pages-deploy-action/commit/9161a5b4c6a49e7463380d18f4cdd47b35228ff0
> Feat: add support for absolute paths

- .eslintrc.json
- __tests__/git.test.ts
- __tests__/main.test.ts
- package.json
- tsconfig.lint.json
I noticed the eslint plugin in VS Code to be unhappy about the test files, so I figured I might be able to fix this.
Run `yarn lint`, and open test files in vs code.
Not sure which target branch to use for this ;-)
> Set up eslint for test files.

- .github/workflows/codeql-analysis.yml
Also, add the dev and release branches, and drop master.
There's some warnings on https://github.com/JamesIves/github-pages-deploy-action/actions/runs/415137521, which  I hope to have fixed here. Also, we use more branches now, and not master anymore.
> Adjust codeql action to latest recommendations

- .github/workflows/production.yml
Keep `lib` and `node_modules` up-to-date on release branches.
I've pushed this to `release/v4` on my fork to test.
PR to follow-up on the conversation in https://github.com/JamesIves/github-pages-deploy-action/discussions/524#discussioncomment-193923
> Add workflow to update build and node_modules on release branches

- .eslintrc.json
- .github/workflows/build.yml
- __tests__/env.js
- __tests__/git.test.ts
- __tests__/main.test.ts
- __tests__/util.test.ts
- __tests__/worktree.error.test.ts
- __tests__/worktree.test.ts
- action.yml
- src/constants.ts
- src/git.ts
- src/worktree.ts
> Add a build step to create lib and node_modules artifact
> Add an integration test to run on PRs
> Happens as part of this PR.
> I bet the integration test will fail for insufficient permissions. We'll see.
> Test current code base as an integration test for PRs and pushes

- README.md
- __tests__/git.test.ts
- action.yml
- src/constants.ts
- src/git.ts
As this change is subtle, I'm taking the opportunity to change
the underscore for the hyphen, which makes it less likely that
users of this action will just pass in an old json array.
I also contemplated if it's a good idea to try to be backwards compatible, i.e., if it's just a single line, try to parse, etc. I didn't feel good about adding the baggage going forwards, though.
> Use multi-line string for clean-exclude patterns.

- __tests__/ssh.test.ts
- src/ssh.ts
Resolves SSH issues #586
* Test on releases/v4-beta
Used child_process as it seems a little better geared for this sort of operation.
> SSH issues
